### ISSUE TITLE
Megabytes calcuation?

### ISSUE THREAD

**Issue by senorezi** [Nuix/Tiered-Report#6]
This app does not support megabytes calculation for the sheets. I believe fileSizeUnit is calculated in the java classes and passed to the .rb file.

**Comment by JuicyDragon** [comment]
Hello @senorezi I saw mention of this over on [the forums](https://forums.nuix.com/t/use-tieredreport-to-calculate-megabytes/1561) and have been making changes to it this morning.  I think I am close to having something ready to go so should hopefully have a new release to support this soon 😄

**Comment by JuicyDragon** [comment]
Fix for this available in [v1.25.0](https://github.com/Nuix/Tiered-Report/releases/tag/v1.25.0)
